feat: editor option

diff --git a/work b/work
--- a/work
+++ b/work
@@ -2,30 +2,46 @@
 
 SHOULD_KILL=true
 MAX_DEPTH=3
+EDITOR="zed"
 
 while [[ "$#" -gt 0 ]]; do
 	case "$1" in
-		--nk) SHOULD_KILL=false ;;
+		--nk)
+			SHOULD_KILL=false
+			;;
 		--depth)
-		  shift
-		  MAX_DEPTH="$1"
-		  ;;
-		*) echo "Unknown parameter: $1" >&2; exit 1;;
+			shift
+			MAX_DEPTH="$1"
+			;;
+		--e)
+			shift
+			EDITOR="$1"
+				;;
+		*)
+			echo "Unknown parameter: $1" >&2
+			exit 1
+			;;
 	esac
 	shift
 done
 
-
-if [[ "$1" == "--nk" ]]; then
-	SHOULD_KILL=false
-fi
-
-
 DIR=$(find ~/coding -maxdepth "$MAX_DEPTH" -type d | fzf)
 [ -z "$DIR" ] && exit 1
 
-code "$DIR" &
+case "$EDITOR" in
+	zed)
+		zeditor "$DIR" &
+		;;
+	code|vscode)
+		code "$DIR" &
+		;;
+	*)
+		echo "Invalid editor: $EDITOR"
+		echo "Supported editors: zed, code"
+		exit 1
+		;;
+esac
 
 if $SHOULD_KILL; then
-	hyprctl dispatch killwindow class:kitty 
+	hyprctl dispatch killwindow class:kitty
 fi
